background = "#050505"
foreground = "#bfbfbf"

cursor = "#ffffff"
accent = "#00d7d7"

selection_foreground = "#000000"
selection_background = "#00aaaa"

color0  = "#000000"
color1  = "#d70000"
color2  = "#00d700"
color3  = "#d7d700"
color4  = "#3f5fff"
color5  = "#d700d7"
color6  = "#00d7d7"
color7  = "#d0d0d0"
color8  = "#909090"
color9  = "#ff5f5f"
color10 = "#5fff5f"
color11 = "#ffff5f"
color12 = "#6c6cff"
color13 = "#ff5fff"
color14 = "#5fffff"
color15 = "#ffffff"
