$activeBorderColor = rgba(d700d7ff)
$inactiveBorderColor = rgba(303030ff)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
